version: '2'

services:

    drupal:
        image: custom-drupal
        build: .
        ports:
            - '8080:80' 
        volumes:
            - drupal-modules:/var/www/html/modules
            - drupal-profiles:/var/www/html/profiles
            - drupal-themes:/var/www/html/themes 
            - drupal-site:/var/www/html/sites
        depends_on:
            - postgres

    postgres:
        image: postgres
        volumes:
            - drupal-data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: example

volumes:
    drupal-data:
    drupal-modules:
    drupal-profiles:
    drupal-themes:
    drupal-site:
